### ISSUE TITLE
**Student Skills Checklist**

### ISSUE THREAD

**Issue by NisargRhino** [NisargRhino/nisarg_shahstudent2025#2]
**Student Skills Checklist**

- [x] **Laptop Verification or Cloud Workspace**
  - Rank: 0
  - Notes: verification by Linux commands notebook

- [x] **VSCode**
  - Rank: 0
  - Notes: live change code, commit, make, run localhost, test, debug

- [x] **Show VSCode GitLens**
  - Rank: 0
  - Notes: verify commits, show change, comments, reset to commit, run on old commit

- [x] **GitHub cloud repo**
  - Rank: 0
  - Notes: live push change, verify id, review profile

- [x] **GitHub Pages Actions**
  - Rank: 0
  - Notes: review runs and verify runtime, receive demo

- [x] **Hacks Tools & Equipment Play**
  - Rank: 0
  - Notes:

- [x] **Hacks GitHub Pages Playground**
  - Rank: 0
  - Notes:

- [x] **Hacks SASS Basics**
  - Rank: 0
  - Notes:

- [x] **Hacks Jupyter Notebook**
  - Rank: 0
  - Notes:

- [x] **Pair Programming**
  - Rank: 0
  - Notes: tangibles that show co-operative work

_Originally posted by @jm1021 in https://github.com/nighthawkcoders/portfolio_2025/issues/14#issuecomment-2237380182_

| Skill | Mastered (Y/N) | Link | Notes |
| -- | -- | -- | -- |
| Laptop Verification or Cloud Workspace | Y | [Link](https://nisargrhino.github.io/nisarg_shahstudent2025/2024/08/25/captures.html) | verification by Linux commands notebook |
| VSCode | Y | [Link](https://nisargrhino.github.io/nisarg_shahstudent2025/2024/08/25/captures.html) | live change code, commit, make, run localhost, test, debug |
| Show VSCode GitLens | Y | [Link](https://nisargrhino.github.io/nisarg_shahstudent2025/2024/08/25/captures.html) | verify commits, show change, comments, reset to commit, run on old commit |
| GitHub student_2025 repo | Y | [Link](https://nisargrhino.github.io/nisarg_shahstudent2025/) | template create, push changes, verify id, review analytics |
| GitHub Pages Actions | Y | [Link](https://nisargrhino.github.io/nisarg_shahstudent2025/blogs/) | review runs and verify runtime, receive demo |
| Hacks Tools & Equipment Play | Y | [Link](http://127.0.0.1:4100/nisarg_shahstudent2025/2024/09/03/MiniGame.html) | Hacks |
| Hacks GitHub Pages Playground | Y | [Link](https://nisargrhino.github.io/nisarg_shahstudent2025/) | Hacks |
| Hacks SASS Basics | Y | [Link](https://nisargrhino.github.io/nisarg_shahstudent2025/) | Hacks |
| Hacks Frontend | Y | [Link](https://nisargrhino.github.io/nisarg_shahstudent2025/) | Hacks |
| Pair Programming | Y | [Link](http://127.0.0.1:4100/nisarg_shahstudent2025/2024/09/03/MiniGame.html) | tangibles that show coop work |

**Comment by Imaad08** [comment]
Imaad Muzaffer's comment
One thing I really liked was the 3D molecule viewer because I also have done chem and something like this would be very helpful. I also liked the minesweeper game because I know from experience that minesweeper is a pretty hard game to code and I appreciate the work that went into it. One thing you could change is the theme since it is the base black theme. Another thing that you could change is the white color background on the about page since it is a very strong contrast.

**Comment by tanav-kambhampati** [comment]
Tanav Review for Nisarg

Here's some things I like...
- I was really impressed by the chemistry molecule models, it's cool how you can drag it around and see the different orientations of the molecule. 
- I also liked the minsweeper game, and the coolest part is that it is able to randomize the mines everytime you refresh the page

What I didn't like...
- I don't like how you can hit the mine first try. In traditional minesweeper, the mines actually load after your first attempt. 
- I also wish I was able to see the functionality of the mini mortenson on the page saying code code code. However, errors do happen.

**Comment by tanayshah1** [comment]
Tanay Shah's Comment: 

I really like Nisarg's 3D molecule viewer because we were in the same AP Chem class last year. Seeing him continue his interest in chemistry beyond that class allows me to connect with him a lot more. In addition to that, I really enjoyed seeing the minesweeper game. I used to play it a lot when I was younger and seeing someone else also interested in it makes me feel nice.

One improvement I would like to see would be a more interesting about me page. It doesn't have much color and is just black and white. Possibly adding a third color that adds a little bit more pop. I would also like to see the miniature Mr. Mortenson that says "Code Code Code." However that currently has some errors.

**Comment by AidanLau10** [comment]
Aidan Lau Review for Nisarg Shah

Pros:
- If I wanted to visualize chemistry compounds more, I would definitely use it because its interactive and has a wide variety of compounds
- I like your home page and that icon on the side. I also like the blue background and border around your headers

Recommendations:
- Another feature you could add is a key for different elements/atoms. If I didn't know chemistry, I wouldn't know what each element in the compound is. 
- It would become a really helpful educational tool if you gave tips on learning or taking chemistry and useful resources. Maybe even tips and tricks for learning topics.

**Comment by Dabear14** [comment]
Hi Nisarg, 
I really liked your 3D molecule viewer and how it was interactive. I think adding something in your about page about your experience with chemistry or styling your page to focus more on that would help it become more unique to you. Also, I really liked the minesweeper game we developed together although I would suggest making some stylistic edits to make it look more unique. 
Thanks, 
Dinesh Sahai
